import { describe, expect, it } from "vitest";
import { buildNewsletterOperationalSummary } from "../../src/newsletter/summary.js";

describe("newsletter/summary", () => {
  it("최근 7일 기준 운영 요약을 집계한다", () => {
    const summary = buildNewsletterOperationalSummary({
      recipients: [
        { email: "alpha@example.com", createdAt: "2026-04-01 09:00:00", updatedAt: "2026-04-01 09:00:00" },
        { email: "beta@example.com", createdAt: "2026-04-02 09:00:00", updatedAt: "2026-04-02 09:00:00" },
      ],
      recipientGroups: [
        {
          id: "group-1",
          name: "정책팀",
          emails: ["alpha@example.com", "beta@example.com"],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
        },
      ],
      searchPresets: [
        {
          id: "preset-1",
          name: "AI 최근 1개월",
          query: {
            keyword: "인공지능",
            datePreset: "1m",
            dateFrom: null,
            dateTo: null,
            noticeScope: "include_closed",
            sortBy: "relevance",
            pageSize: 20,
          },
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
        },
      ],
      subscriptionTemplates: [
        {
          id: "subscription-1",
          name: "AI 정책 브리핑",
          query: {
            keyword: "인공지능",
            datePreset: "1m",
            dateFrom: null,
            dateTo: null,
            noticeScope: "include_closed",
            sortBy: "relevance",
            pageSize: 20,
          },
          recipientGroupId: null,
          recipientGroupName: null,
          searchPresetId: null,
          searchPresetName: null,
          recipients: ["alpha@example.com"],
          subject: "AI 정책 브리핑",
          introText: null,
          outroText: null,
          recurrence: "daily",
          onlyNewResults: true,
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
        },
      ],
      schedules: [
        {
          id: "job-1",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "daily",
          status: "pending",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "AI 정책 브리핑",
            includeAllResults: true,
            recipients: ["alpha@example.com"],
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: null,
          lastRunMessage: null,
          errorMessage: null,
        },
        {
          id: "job-2",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "weekly",
          status: "paused",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "보건의료 브리핑",
            includeAllResults: true,
            recipients: ["beta@example.com"],
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: null,
          lastRunMessage: null,
          errorMessage: null,
        },
        {
          id: "job-3",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "weekly",
          status: "failed",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "산업 정책 브리핑",
            includeAllResults: true,
            recipients: ["gamma@example.com"],
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: "failed",
          lastRunMessage: "SMTP timeout",
          errorMessage: "SMTP timeout",
        },
      ],
      scheduleRuns: [
        {
          id: "run-1",
          scheduleJobId: "job-1",
          scheduleSubject: "AI 정책 브리핑",
          recurrence: "daily",
          status: "sent",
          message: null,
          keyword: "인공지능",
          itemCount: 3,
          sentCount: 2,
          failedCount: 0,
          deliveryJobId: "delivery-1",
          runAt: "2026-04-20 10:30:00",
        },
        {
          id: "run-2",
          scheduleJobId: "job-2",
          scheduleSubject: "보건의료 브리핑",
          recurrence: "weekly",
          status: "failed",
          message: "SMTP timeout",
          keyword: "보건의료",
          itemCount: 0,
          sentCount: 0,
          failedCount: 0,
          deliveryJobId: null,
          runAt: "2026-04-18 11:00:00",
        },
        {
          id: "run-3",
          scheduleJobId: "job-3",
          scheduleSubject: "산업 정책 브리핑",
          recurrence: "weekly",
          status: "skipped",
          message: "조건에 맞는 법안 없음",
          keyword: "산업",
          itemCount: 0,
          sentCount: 0,
          failedCount: 0,
          deliveryJobId: null,
          runAt: "2026-04-19 08:00:00",
        },
        {
          id: "run-4",
          scheduleJobId: "job-3",
          scheduleSubject: "오래된 이력",
          recurrence: "weekly",
          status: "sent",
          message: null,
          keyword: "오래됨",
          itemCount: 1,
          sentCount: 1,
          failedCount: 0,
          deliveryJobId: "delivery-old",
          runAt: "2026-04-10 08:00:00",
        },
      ],
      sendLogs: [
        {
          id: "log-1",
          jobId: "delivery-1",
          recipientEmail: "alpha@example.com",
          status: "sent",
          errorMessage: null,
          subject: "AI 정책 브리핑",
          keyword: "인공지능",
          itemCount: 3,
          snapshotAvailable: true,
          sentAt: "2026-04-20 10:31:00",
        },
        {
          id: "log-2",
          jobId: "delivery-1",
          recipientEmail: "beta@example.com",
          status: "failed",
          errorMessage: "Mailbox unavailable",
          subject: "AI 정책 브리핑",
          keyword: "인공지능",
          itemCount: 3,
          snapshotAvailable: true,
          sentAt: "2026-04-20 10:31:00",
        },
        {
          id: "log-3",
          jobId: "delivery-old",
          recipientEmail: "old@example.com",
          status: "sent",
          errorMessage: null,
          subject: "오래된 발송",
          keyword: "오래됨",
          itemCount: 1,
          snapshotAvailable: true,
          sentAt: "2026-04-11 09:00:00",
        },
      ],
      now: "2026-04-21T00:00:00+09:00",
    });

    expect(summary.recipientCount).toBe(2);
    expect(summary.recipientGroupCount).toBe(1);
    expect(summary.searchPresetCount).toBe(1);
    expect(summary.subscriptionTemplateCount).toBe(1);
    expect(summary.scheduleCounts).toEqual({
      total: 3,
      active: 1,
      paused: 1,
      failed: 1,
    });
    expect(summary.scheduleRunCounts).toEqual({
      sent: 1,
      skipped: 1,
      failed: 1,
    });
    expect(summary.sendLogCounts).toEqual({
      sent: 1,
      failed: 1,
    });
    expect(summary.scheduleRunWindowDays).toBe(7);
  });
});
