import { describe, expect, it } from "vitest";
import { buildNewsletterSubscriptionActivity } from "../../src/newsletter/subscription-activity.js";

describe("newsletter/subscription-activity", () => {
  it("구독 템플릿별 연결 예약 수와 최근 실행 결과를 계산한다", () => {
    const records = buildNewsletterSubscriptionActivity(
      [
        {
          id: "subscription-1",
          name: "AI 정책 브리핑",
          query: {
            keyword: "인공지능",
            datePreset: "1m",
            dateFrom: null,
            dateTo: null,
            noticeScope: "include_closed",
            sortBy: "relevance",
            pageSize: 20,
          },
          recipientGroupId: null,
          recipientGroupName: null,
          searchPresetId: null,
          searchPresetName: null,
          recipients: ["alpha@example.com"],
          subject: "AI 정책 브리핑",
          introText: null,
          outroText: null,
          recurrence: "daily",
          onlyNewResults: true,
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
        },
        {
          id: "subscription-2",
          name: "보건의료 브리핑",
          query: {
            keyword: "보건의료",
            datePreset: "1m",
            dateFrom: null,
            dateTo: null,
            noticeScope: "include_closed",
            sortBy: "relevance",
            pageSize: 20,
          },
          recipientGroupId: null,
          recipientGroupName: null,
          searchPresetId: null,
          searchPresetName: null,
          recipients: ["beta@example.com"],
          subject: "보건의료 브리핑",
          introText: null,
          outroText: null,
          recurrence: "weekly",
          onlyNewResults: false,
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
        },
      ],
      [
        {
          id: "job-1",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "daily",
          status: "pending",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "AI 정책 브리핑",
            includeAllResults: true,
            recipients: ["alpha@example.com"],
            subscriptionTemplateId: "subscription-1",
            subscriptionTemplateName: "AI 정책 브리핑",
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: null,
          lastRunMessage: null,
          errorMessage: null,
        },
        {
          id: "job-2",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "weekly",
          status: "paused",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "AI 정책 브리핑 2",
            includeAllResults: true,
            recipients: ["alpha@example.com"],
            subscriptionTemplateId: "subscription-1",
            subscriptionTemplateName: "AI 정책 브리핑",
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: null,
          lastRunMessage: null,
          errorMessage: null,
        },
        {
          id: "job-3",
          scheduledAt: "2026-04-22T00:00:00.000Z",
          recurrence: "weekly",
          status: "failed",
          payload: {
            query: {},
            items: [],
            selectedBillIds: [],
            subject: "보건의료 브리핑",
            includeAllResults: true,
            recipients: ["beta@example.com"],
            subscriptionTemplateId: "subscription-2",
            subscriptionTemplateName: "보건의료 브리핑",
          },
          deliveredBillIds: [],
          createdAt: "2026-04-01 09:00:00",
          updatedAt: "2026-04-01 09:00:00",
          processedAt: null,
          lastRunStatus: "failed",
          lastRunMessage: "SMTP timeout",
          errorMessage: "SMTP timeout",
        },
      ],
      [
        {
          id: "run-1",
          scheduleJobId: "job-1",
          scheduleSubject: "AI 정책 브리핑",
          recurrence: "daily",
          status: "sent",
          message: null,
          keyword: "인공지능",
          itemCount: 3,
          sentCount: 1,
          failedCount: 0,
          deliveryJobId: "delivery-1",
          runAt: "2026-04-20 10:00:00",
        },
        {
          id: "run-2",
          scheduleJobId: "job-2",
          scheduleSubject: "AI 정책 브리핑",
          recurrence: "weekly",
          status: "failed",
          message: "no new bills",
          keyword: "인공지능",
          itemCount: 0,
          sentCount: 0,
          failedCount: 0,
          deliveryJobId: null,
          runAt: "2026-04-21 11:00:00",
        },
        {
          id: "run-3",
          scheduleJobId: "job-3",
          scheduleSubject: "보건의료 브리핑",
          recurrence: "weekly",
          status: "failed",
          message: "SMTP timeout",
          keyword: "보건의료",
          itemCount: 0,
          sentCount: 0,
          failedCount: 0,
          deliveryJobId: null,
          runAt: "2026-04-21 09:00:00",
        },
      ],
    );

    expect(records).toHaveLength(2);
    expect(records[0]).toMatchObject({
      subscriptionId: "subscription-1",
      scheduleCount: 2,
      activeScheduleCount: 1,
      pausedScheduleCount: 1,
      failedScheduleCount: 0,
      latestRunStatus: "failed",
      latestRunAt: "2026-04-21 11:00:00",
      latestRunMessage: "no new bills",
      latestSnapshotJobId: "delivery-1",
      latestSnapshotAt: "2026-04-20 10:00:00",
    });
    expect(records[1]).toMatchObject({
      subscriptionId: "subscription-2",
      scheduleCount: 1,
      activeScheduleCount: 0,
      pausedScheduleCount: 0,
      failedScheduleCount: 1,
      latestRunStatus: "failed",
      latestRunAt: "2026-04-21 09:00:00",
      latestRunMessage: "SMTP timeout",
      latestSnapshotJobId: null,
      latestSnapshotAt: null,
    });
  });
});
